name: compound-annotator
channels:
  - conda-forge
dependencies:
  - python=3.10
  - requests=2.28.2
  - pandas=1.5.3
  - numpy=1.24.2
  - tqdm=4.64.1
  - rdkit=2022.9.4
  - pymysql=1.0.2
  - csvkit=1.1.0
  - pip>=21.2.4
  - black>=23.0.0
  - ipykernel>=6.21.2
  - jupyter>=1.0.0
  - fire>=0.4.0
